version: "3"
services:
  # Node.js Application Service
  app:
    image: techvoyag/ca4frontend:lastest
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - db

  # MongoDB Database Service
  db:
    image: techvoyag/ca4db:lastest
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
