name: Docker Image CI

on:
  push:
    branches: [ "p200199" ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag techvoyag/ca4frontend:latest
    - name: Push Docker image
      run: |
          docker tag techvoyag/ca4frontend:latest ${{ secrets.DOCKER_USERNAME }}/techvoyag/ca4frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/techvoyag/ca4frontend:latest
